baseURL = "/"
languageCode = "en-us"
title = "Jordan Krogmann"
description = "An easy reading blog for all things math, programming, and sarcasm."
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Jordan Krogmann"
    description = "An easy reading blog for all things math, programming, and sarcasm."
    logo = "favicon/android-chrome-192x192.png"
    twitterAuthor = "@jordan_krogmann"
    githubUsername = "jordan-krogmann"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

    
[[menu.main]]
    url = "/tags/"
    name = "Tags"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:jordanckrogmann@gmail.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Jordan-Krogmann"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jordan_krogmann"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/jordan-krogmann-41ab348a/"
    name = "fab fa-linkedin"
    weight = 4


